export default {
  date: "التاريخ",
  time: "الوقت",
  newTasks: "طلبات بانتظار عروض,",
  addYourOffer: "إضافة عرض جديد",
  send: "إرسال",
  status: "الحالة",
  completed: "مكتمل",
  waitingPayment: "في إنتظار الدفع",
  inProgress: "جاري التنفيذ",
  view: "عرض",
  yourTasks: "مهامك,",
  login: "تسجيل الدخول",
  register: "التسجيل",
  welcomeBack: "مرحبا بعودتك",
  signinTo: "يرجي تسجيل الدخول لتستمتع بخدمات تطبيق هوم جوب",
  yourPhone: "رقم الجوال",
  yourPassword: "كلمة المرور",
  firstname: "الاسم الاول",
  lastname: "الاسم الاخير",
  yourmail: "البريد الإلكتروني",
  forgotPassword: "نسيت كلمة المرور",
  dontHaveAccount: "ليس لديك حساب ؟",
  city: "المدينة",
  location: "الموقع",
  range: "المحيط الذي تقدم خدمتك به",
  servicesType: "نوع الخدمة",
  phoneNum: "رقم الجوال",
  commercialRegister: "السجل التجاري",
  chooseBank: "إختر المصرف",
  bankAccount: "الحساب المصرفي (IBAN)",
  password: "كلمة المرور",
  confirmPassword: "تأكيد كلمة المرور",
  continue: "إستمرار",
  enterYourNum: "يرجي إدخال رقم الجوال",
  pleaseEnterYourNum:
    "يرجي إدخال رقم الجوال وسيتم إرسال كود التفعيل",
  mobileNum: "رقم الجوال",
  verifyNum: "تأكيد رقم الجوال",
  enterPin: "يرجي إدخال الكود المرسل في الرسالة النصية",
  enterCode: "أدخل الكود",
  resendCode: "إعادة إرسال الكود",
  editNum: "تعديل رقم الجوال",
  enterNewPassword: "يرجي إدخال كلمة المرور الجديدة",
  passwordPlaceholder: "************",
  cancel: "إلغاء",
  homeService: "Home Job,",
  earn: "أحصل علي",
  and: "و",
  appRatio: "نسبة التطبيق",
  price: "السعر",
  offer: "لماذا أنت الأفضل لهذه المهمة",
  myProfile: "حسابي,",
  newPassword: "كلمة المرور الجديدة",
  accountInformation: "بيانات الحساب",
  requestsHistory: "سجل الطلبات",
  upload: "رفع",
  done: "منتهي",
  cancelled: "ملغي",
  underPayment: "بإنتظار الدفع",
  waitingOffers: "بإنتظار عروض",
  introText: "أعثر على الأشخاص بالمهارات التي تحتاجها على هوم جوب",
  offers: "عروض",
  yourRequests: "طلباتك,",
  confirm: "تأكيد",
  accept: "قبول",
  whatDoYouWant: "ماذا تحتاج ؟",
  budget: "الميزانية",
  paymentMethod: "طريقة الدفع",
  newTask: "مهمة جديدة",
  agreedToYourOffer: "تم الموافقو علي طلبك",
  newMessageFrom: "رسال",
  newOfferFrom: "عرض جديد من ",
  notifications: "الإشعارات,",
  iamClient: "التسجيل كعميل",
  iamEmployee: "التسجيل كمقدم خدمة",
  youHaveAnAccount: "هل لديك حساب؟",
  welcome: "مرحبا",
  signUpToContinue: "يرجي التسجيل لإستخدام التطبيق",
  clients: "عملاء",
  tasks: "المهام",
  chat: "الدردشة",
  logout: "تسجيل الخروج",
  requests: "الطلبات",
  history: "السجل",
  myprofile: "حسابي",
  notification: "الإشعارات",
  Services: "الخدمات",
  signUp: "تسجيل",
  city: "المدينة",
  theRangeYouWillBeWorkingOn: "المحيط الذي تقدم خدمتك به",
  services: "نوع الخدمات",
  save: "حفظ",
  CommercialRegister: "السجل التجاري",
  typeHere: "أكتب هنا...",
  conversions: "المحادثات",
  addOffer: "إضافة عرض",
  request: "طلب",
  newRequest: "طلب جديد",
  invalidPhone: "رقم جوال غير صحيح",
  invalidPassword: "يرجي إدخال 6 أحرف علي الأقل",
  passwordNotMatch: "كلمة المرور غير مطابقة",
  invalidName: "يرجي إدخال 3 أحرف علي الأقل",
  invalidMail: "يرجي إدخال بريد إلكتروني صحيح",
  invalidPrice: "يرجي إدخال السعر",
  invalidOfferDetails: "يرجي إدخال تفاصيل العرض",
  serviceValues: "تقييم الخدمة",
  from: "من",
  Service: "خدمة",
  invalidRequestDetails: "يرجي إدخال تفاصيل الطلب",
  invalidBudget: "يرجي إدخال الميزانية",
  chooseDate: "يرجي اختيار التاريخ",
  chooseTime: "يرجي اختيار الوقت",
  enterInfo: "يرجي إدخال معلومات حسابك",
  cash: "نقدي",
  chooseCity: "يرجي اختيار المدينة",
  chooseRange: "يرجي اختيار المحيط الذي تقدم خدمتك به",
  chooseService: "يرجي اختيار الخدمة",
  noCategory: "لا يوجد أقسام",
  noConversations: "لا يوجد محادثات",
  noRequests: "لا يوجد طلبات",
  noNotifications: "لا يوجد إشعارات",
  noRequestsHistory: "لا يوجد سجل",
  invalidBankAccount: "حساب مصرفي غير صحيح",
  invalidCommerical: "سجل تجاري غير صحيح",
  invalidCode: "كود تفعيل غير صحيح ",
  noOffers: "لا يوجد عروض",
  noMessages: "لا يوجد رسائل",
  noHistory: "لا يوجد سجل",
  editYourProfile: "تعديل الحساب,",
  chooseYourLocation: "يرجي اختيار الموقع",
  chooseServiceAndLetsStart: "اختر خدمة و لنبدأ",
  choosePhoto: "يرجي اختيار صورة",
  dataChanged: "تم تغيير التاريخ بنجاح",
  noTasks: "لا يوجد مهام",
  dontHaveTasks: "مهامك خالية",
  choosePaymentMethod: "يرجي اختيار طريقة الدفع",
  image: "صورة",
  voiceMassage: "رسالة صوتية",
  newMassage: "رسالة جديدة",
  tryAgain: "إعادة المحاولة",
  somethingWentWrong: "حدث خطأ ما",
  pleaseAddRate: "يرجي إضافة تقييم",
  yourFeedback: "رأيك",
  rateRequired: "التقييم إجباري",
  feedbackRequired: "إضافة رأيك إجباري",
  noReviewYet: "لم يقيّم بعد",
  recieved: 'تم الاستلام',
  takePhotoButtonTitle: "التقاط صورة",
  chooseFromLibraryButtonTitle: "فتح معرض الصور",
  changeLang:'النسخة الانجليزية',
  confirmRestart:'سيتطلب هذا الاجراء اعادة تشغيل التطبيق',
  changeLangIntro:'English Version',
  communicate:'مراسلة',
  transactions:'المعاملات',
  totalBalance:'اجمالي الرصيد',
  currency: "ر.س",
  reject: "رفض",
  offerRejected: "العرض مرفوض",
  whatsapp: "واتس آب",
  twitter: "تويتر",
  paymentSuccess: "نجحت عملية الدفع",
  paymentFailed: "فشلت عملية الدفع",
};
