export default {
    date: "Date",
    time: "Time",
    newTasks: "Waiting Orders,",
    addYourOffer: "Add your offer",
    send: "Send",
    status: "Status",
    completed: "Completed",
    waitingPayment: "Waiting payment",
    inProgress: "In progress",
    view: "View",
    yourTasks: "Your Tasks,",
    login: "Login",
    register: "Register",
    welcomeBack: "Welcome Back",
    signinTo: "Sign in to continue using Home Job app",
    yourPhone: "Your Phone",
    yourPassword: "Your Password",
    firstname: "First Name",
    lastname: "Last Name",
    yourmail: "Your E-Mail",
    forgotPassword: "Forgot my password",
    dontHaveAccount: "Don't have an account? ",
    city: "City",
    location: "Location",
    range: "The range you will be working on",
    servicesType: "Services Type",
    phoneNum: "Phone Number",
    commercialRegister: "Commercial Register",
    chooseBank: "Choose Bank",
    bankAccount: "Bank Account (IBAN)",
    password: "Password",
    confirmPassword: "Confirm Password",
    continue: "Continue",
    enterYourNum: "Enter your mobile number",
    pleaseEnterYourNum: "Please enter your mobile number and we will send the code",
    mobileNum: "Mobile number",
    verifyNum: "Verify your mobile number",
    enterPin: "Enter the pin you have received via SMS on ",
    enterCode: "Enter the code",
    resendCode: "Resend Code",
    editNum: "Edit Number",
    enterNewPassword: "Enter your new password",
    passwordPlaceholder: "************",
    cancel: "Cancel",
    homeService: "Home Job,",
    earn: "Earn",
    and: "and",
    appRatio: "app ratio",
    price: "Price",
    offer: "Why are you the best for this job",
    myProfile: "My Profile,",
    newPassword: "New Password",
    accountInformation: "Account Informations",
    requestsHistory: "Requests History",
    upload: "Upload",
    done: "Done",
    cancelled: "Cancelled",
    underPayment: "Under payment",
    waitingOffers: "Waiting offers",
    introText: "Find the people with the skills you need on home job",
    ryad: "Ryad",
    offers: "Offers",
    yourRequests: "Your Requests,",
    confirm: "Confirm",
    accept: "Accept",
    whatDoYouWant: "What do you want ?",
    budget: "Budget",
    paymentMethod: "Payment method",
    continue: "Continue",
    newTask: "New Task",
    agreedToYourOffer: "agreed to your offer",
    newMessageFrom: "New Message From ",
    newOfferFrom: "New offer from ",
    notifications: "Notifications,",
    iamClient: "I'm a Client",
    iamEmployee: "I'm an employee",
    youHaveAnAccount: "You have an account? ",
    welcome: "Welcome",
    signUpToContinue: "Sign up to continue using Home Job app",
    clients: "Clients",
    tasks: "Tasks",
    chat: "Chat",
    logout: "Logout",
    requests: "Requests",
    history: "History",
    myprofile: "My Profile",
    notification: "Notifications",
    Services: "Services",
    signUp: "Sign Up",
    city: "City",
    location: "Location",
    theRangeYouWillBeWorkingOn: "The range you will be working on",
    services: "Services Type",
    commercialRegister: "Commercial Register",
    chooseBank: "Choose Bank",
    bankAccount: "Bank Account",
    password: "Password",
    confirmPassword: "Confrim Password",
    continue: "Continue",
    enterYourNum: "Enter your mobile number",
    pleaseEnterYourNum: "Please enter your mobile number and well send the code",
    mobileNum: "Mobile number",
    verifyNum: "Verify your mobile number",
    enterPin: "Enter the pin you have received via SMS on ",
    enterCode: "Enter the code",
    resendCode: "Resend Code",
    editNum: "Edit Number",
    enterNewPassword: "Enter your new password",
    passwordPlaceholder: "************",
    cancel: "Cancel",
    homeService: "Home Job,",
    earn: "Earn",
    and: "and",
    appRatio: "app ratio",
    price: "Price",
    offer: "Offer",
    myProfile: "My Profile,",
    newPassword: "New Password",
    accountInformation: "Account Informations",
    requestsHistory: "Requests History",
    upload: "Upload",
    done: "Done",
    cancelled: "Cancelled",
    underPayment: "Under payment",
    waitingOffers: "Waiting offers",
    introText: "Find the people with the skills you need on home job",
    ryad: "Ryad",
    offers: "Offers",
    yourRequests: "Your Requests,",
    confirm: "Confirm",
    whatDoYouWant: "What do you want ?",
    budget: "Budget",
    continue: "Continue",
    newTask: "New Task",
    agreedToYourOffer: "agreed to your offer",
    newMessageFrom: "New Message From ",
    newOfferFrom: "New offer from ",
    notifications: "Notifications,",
    save: "Save",
    cancel: "Cancel",
    CommercialRegister: "Commercial Register",
    iamClient: "I'm a Client",
    iamEmployee: "I'm an employee",
    youHaveAnAccount: "You have an account? ",
    welcome: "Welcome",
    signUpToContinue: "Sign up to continue using Home Job app",
    typeHere: "Type Here...",
    history: "History",
    conversions: "Conversations",
    addOffer: "Add Offer",
    request: "Request",
    newRequest: "New Request",
    invalidPhone: "Invalid Phone Number",
    invalidPassword: "Please, enter password contains 6 characters at least",
    passwordNotMatch: "Passwords not match",
    invalidName: "Please, enter name contains 3 characters at least",
    invalidMail: "Please, enter valid e-mail address",
    invalidPrice: "Enter your price",
    invalidOfferDetails: "Enter your offer details",
    serviceValues: "Service values",
    from: "From",
    Service: "Service",
    invalidRequestDetails: "Enter your request details",
    invalidBudget: "Enter your budget",
    chooseDate: "Choose date",
    chooseTime: "Choose time",
    enterInfo: "Please enter your Profile informations",
    cash: "Cash",
    chooseCity: "Choose city",
    chooseRange: "Choose Range you will be working on",
    chooseService: "Choose service",
    noCategory: "No Category",
    noConversations: "No Conversations",
    noRequests: "No Requests",
    noNotifications: "No Notifications",
    noRequestsHistory: "No Requests History",
    invalidBankAccount: "Invalid bank account",
    invalidCommerical: "Invalid Commerical Register",
    invalidCode: "Invalid verification code",
    noOffers: "No Offers",
    noMessages: "No Messages",
    noHistory: "No History",
    editYourProfile: "Edit Your Profile,",
    chooseYourLocation: "Choose Your Location",
    chooseServiceAndLetsStart: "Choose service and let's start",
    choosePhoto: "Choose Photo",
    dataChanged: "Data changed successfully",
    noTasks: "No Tasks",
    dontHaveTasks: "Your Tasks is empty",
    choosePaymentMethod: "Choose Payment Method",
    image: "Image",
    voiceMassage: "Voice Massage",
    newMassage: "New Message(s)",
    tryAgain: "Try Again",
    somethingWentWrong: "Something Went Wrong",
    pleaseAddRate: "Please Add Rate",
    yourFeedback:'Your Feedback',
    rateRequired:'Rate is Required',
    feedbackRequired:'Feedback is Required',
    noReviewYet: "No Review Yet",
    recieved:'Recieved',
    takePhotoButtonTitle: "Take Photo",
    chooseFromLibraryButtonTitle: "Open Library",
    changeLang:'Arabic version',
    confirmRestart:'This action requires app to restart',
    changeLangIntro:'النسخة العربية',
    communicate:'Chat',
    wallet:'Wallet',
    transactions:'Transactions',
    totalBalance:'Total Balance',
    currency: "SAR",
    reject: "reject",
    offerRejected: "Offer Rejected",
    offerAccepted: "Offer Accepted",
    whatsapp: "WhatsApp",
    twitter: "Twitter",
    paymentSuccess: "Payment Succeeded",
    paymentFailed: "Payment Failed",
  };
  